Add JSON.stringify to enable error on  browser.service.ts
MeshJS/mesh pull request #170
Opened 2023-11-22 15:51 UTC by brian-atriumlab

Add JSON.stringify to enable try/catch error handling

- errors are currently coming back with [Object object] in the message string

2024-01-20 18:38 UTC, wstueve requested changes
This will log '{}'.  See: 

- https://stackoverflow.com/questions/18391212/is-it-not-possible-to-stringify-an-error-using-json-stringify
- https://jsfiddle.net/wstueve/872q15aj/3/

2024-01-20 20:21 UTC, brian-atriumlab commented
> This will log '{}'. See:
> 
> * https://stackoverflow.com/questions/18391212/is-it-not-possible-to-stringify-an-error-using-json-stringify
> * https://jsfiddle.net/wstueve/872q15aj/3/

I am seeing ` [Object object]` in the string currently.

This code is implemented on an error below on line 120, same file, why is this acceptable in this use case? 
![image](https://github.com/MeshJS/mesh/assets/110428175/ac8d337d-42a9-406e-8c73-d71aca676643)

2024-01-21 16:39 UTC, abdelkrimdev approved these changes

2024-01-21 16:40 UTC, merged

2024-01-21 17:01 UTC, wstueve commented
Not sure.  I couldn't get it to print out the correct thing when I tried it in a Fiddle a couple ways.